name: higlass-multicontact
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.7
  - nodejs=12.*
  - cytoolz
  - pysam
  - pip
  - pip:
    - cooler
    - dcicutils
    - higlass-python
    - jupyterlab>=1.1.1
    - ipywidgets>=7.5.1
    - matplotlib
