name: higlass-multicontact
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python>=3.7
  - nodejs=10.*
  - cytoolz
  - pysam
  - pip
  - pip:
    - cooler
    - dcicutils
    - higlass-python
    - ipywidgets==7.5.1
    - jupyterlab==1.1.1
    - matplotlib
